### ISSUE TITLE
Error processing argument at Index 0...

### ISSUE THREAD

**Issue by cicciociccini** [plainlab/plainprinter#17]
## Expected Behavior
Plain printer should start creating the file

## Current Behavior

As soon as i click ''start printing'', an error occurs: Error processing argument at Index 0, conversion failure from... 
TypeError: Error procesing argument at index 0, conversion failure from    at    C:\Users\...\AppData\Local\Programs\plainprinter\resources\app.asar\dist\main\webp...:27 at node:electron/js2c/browser_init:189:563

## Context
I tried to uninstall and re-install plainprinter several times, also trying older versions, but the problem still the same

## Your Environment

Windows 11, PlainPrinter version 0.2.2

**Comment by manhtai** [comment]
Thanks for reporting the bug. Unfortunately I don't have a Windows device to working on this. Glad to accept a MR from others though.

**Comment by toxybenzoic** [comment]
@manhtai The issue should be fixed by my PR. I would be grateful if you could take a look at it when you have the chance.

**Comment by manhtai** [comment]
Released https://github.com/plainlab/plainprinter/releases/tag/v1.0.2
