### ISSUE TITLE
ERROR OPENING THE APPLICATION

### ISSUE THREAD

**Issue by cyberlearn3r** [plainlab/plainprinter#18]
## Expected Behavior

Plain Printer should open.

## Current Behavior

The application gives an error when trying to open. MacOS is marking the application as Malware. Even when you check the "Overridde Malware Protection" box the application gives an error that the application can't be opened. Tried reinstalling but no help.

## Error Report
Exception Type:  EXC_CRASH (SIGKILL (Code Signature Invalid))
Exception Codes: 0x0000000000000000, 0x0000000000000000
Termination Reason: CODESIGNING 1 Taskgated Invalid Signature

## Your Environment
- PlainPrinter version: 0.2.2
- Operating System and version: Intel Processor and MacOS Ventura 13.0.1

**Comment by cyberlearn3r** [comment]
Hello Team,
Please advise if you are able to replicate this bug and if there is any available solution.
Thanks,

**Comment by manhtai** [comment]
Hello, thanks for the report, we're working on it, in the meantime you can try the CLI version here https://github.com/manhtai/vitalsource-printer

**Comment by manhtai** [comment]
Potential bug from electron-builder https://github.com/electron-userland/electron-builder/issues/7244

**Comment by manhtai** [comment]
@cyberlearn3r plz try the latest release here https://github.com/plainlab/plainprinter/releases/tag/v0.2.3, tested on my mac with macOS Monterey 12.6, not ready to upgrade to 13 yet.

**Comment by cyberlearn3r** [comment]
Hello Team,
I tested this on macOS 13.0.1 Ventura and the issue seems to be resolved now.
Thanks for the quick resolution.
