### ISSUE TITLE
spawn ENOENT error on Windows 11

### ISSUE THREAD

**Issue by manhtai** [plainlab/plainprinter#5]
Root cause: https://github.com/bencevans/screenshot-desktop/issues/135

**Comment by ghost** [comment]
Hi, 
this issue unfortunatly still persists.

Is there a workaround?

Running Windows 11 21H2, and PlainPrinter-Setup-0.2.0.exe

Error screenshot below:
![image](https://user-images.githubusercontent.com/31773450/188043195-505f0942-da0f-48b1-9c42-33b7cc7793b5.png)

**Comment by manhtai** [comment]
The open issue above was fixed but not released yet. However I could use the dev version and build a dev release for PlainPrinter. May do that in a few days.

**Comment by ZartanZ** [comment]
Hoping you can get this error resolved soon. I'm using Windows 10 Pro and I get this error.

**Comment by manhtai** [comment]
Attempt at #14, will release a version soon.

**Comment by manhtai** [comment]
@robertschuppan @ZartanZ please try https://github.com/plainlab/plainprinter/releases/tag/v0.2.1, I don’t have a Windows still…

**Comment by ghost** [comment]
Hey,

new error:

**Comment by ZartanZ** [comment]
New error:

**Comment by manhtai** [comment]
Another try, if it doesn't work I'm fraid this issue will open till I get a Windows, please try again @ZartanZ @robertschuppan https://github.com/plainlab/plainprinter/releases/tag/v0.2.2

**Comment by ghost** [comment]
New (?) error:
[image.png]

------- Original Message -------

**Comment by ZartanZ** [comment]
> Another try, if it doesn't work I'm fraid this issue will open till I get a Windows, please try again @ZartanZ @robertschuppan https://github.com/plainlab/plainprinter/releases/tag/v0.2.2

Thank-you very much @manhtai v0.2.2 worked for me. I really appreciate it.

**Comment by manhtai** [comment]
You're welcome!

**Comment by ghost** [comment]
I just saw that the screenshots of the errors did not get uploaded... :-(

I tried out the version 0.2.2 on my Surface Pro X (2019, ARM processor), Windows 11: There was no error message, however, the button klicking didnt work.

**Comment by ghost** [comment]
Got it.

Its not urgent, was just confused as the open issue seemed completed but the bug was still there.

**Comment by manhtai** [comment]
Hi there, @ZartanZ confirmed the bug is fixed and the app works, you didn't see the error anymore then I assumed it is fixed. If you got another issue plz create a new issue. And if possible don't use the reply in email feature. It contains too much unnecessary stuffs.
