### ISSUE TITLE
the screen is all white when clicking the left button of mouse to draw a area, is that a bug ?

### ISSUE THREAD

**Issue by fortheddy** [plainlab/plainprinter#7]
## the screen is all white when clicking the left button of mouse to draw a area

OS version： Windows 11 （21H2 version）
software version： 0.0.5（latest）
 the screen is all white when clicking the left button of mouse to draw a area，and I can't see anything in my screen except the mouse cursor and the rectangle border line when drawing the rectangle。 the software itself works ,but I don't know is that supposed to be the normal behavior，it make me confused when selecting the accurate area the I want to print。

**Comment by manhtai** [comment]
Since I don't have a Windows machine but just upgraded almost all packages now, can you check again with the latest release @splintereddy? Thanks.

**Comment by fortheddy** [comment]
the latest version （0.2.0）works perfect！！！Thank you so much
