### ISSUE TITLE
PlainPrinter for M1 Macs

### ISSUE THREAD

**Issue by etec-masterofsynapse** [plainlab/plainprinter#8]
It is stated in the Readme of the repository that an ARM64 DMG file exists for M1 Macs to run the program.
But the commit https://github.com/plainlab/plainprinter/commit/94ca424ba37e9b3905bc29cf293e9cec8c2e01d9 disabled the ARM64 build.
And the normal DMG app cannot be run on M1 Macs since macOS tells me the app isn't compatible.

When will the ARM64 DMG be available again?

**Comment by manhtai** [comment]
Hello. I‘ve disabled it because some packages were not compatible with M1 yet. I will try to upgrade them again soon!

**Comment by cyb3rw0lf** [comment]
any news?

**Comment by manhtai** [comment]
They are now, will do the upgrade this week.

**Comment by manhtai** [comment]
Supported now from https://github.com/plainlab/plainprinter/releases/tag/v0.1.0

**Comment by cyb3rw0lf** [comment]
For me it doesn't work, error:
`"PlainPrinter.app" is damaged and can't be opened. You should move it to the Bin.`

![2022-08-02_21-26-24](https://user-images.githubusercontent.com/25265715/182457682-c1d27f13-af2e-476c-aed6-a9f6273c4388.png)

**Comment by manhtai** [comment]
@cyb3rw0lf Oh sorry I used the old key to sign it. Use the new key to build now, please try download again.
